---
title: ""
output:
  html_document:
    theme: sandstone
    highlight: kate
    css: Generic.css
    fig_width: 7
    fig_height: 6
    fig_caption: true
---

***

### Hotel and Spa

* Shelley Point has an amazing hotel with a spa (book in advance!), as well as a lovely swimming pool area (you are welcome to use it, provided it is not too full - peak times they might ask if you are hotel residents).

### Restaurants

* There is a great pizza bar called Dorothea's (open 11:00 - 18:00) which has amazing pizzas, cocktails, beer on tap and most weekends live music. Its ~150m from the house. 

* There's also a Cattle Baron restaurant at the top, with a lovely view and great menu.

* We highly recommend going to Alegria restaurant (as you enter St. Helena Bay), and also Gaatjie & Leeto (Paternoster).

### Pubs

* Above the swimming pool at the hotel (about 150m from the house) there's a nice cigar lounge with a pool table - nice for having a beer and overlooking the kids swimming below...

* For the thirsty, [Noordblinder](https://goo.gl/maps/nCvzuv2CW468daEs9) offers a nice easy going West-Coast pub vibe.

* If you have time, go to [Panty Bar](https://goo.gl/maps/cDQva4kc9SjL3pj67) in Paternoster - always a nice experience!

### Amenities

* You can enjoy a round of golf (first hole is ~200m from house), two tennis courts and lawn bowls (150m from the house) - for each you must please book at the golf club next to the hotel.

* Shelley Point Kayaking is also a must - you often see dolfins, sunfish and if you are lucky a whale (Whatsapp: 082 805 5363)

### Beaches

* Be sure to try out [Golden mile beach](https://goo.gl/maps/GsC7KPvfA5DCc3s88), [Light House beach](https://goo.gl/maps/vzUAc24WbHjdLi7X8) and the [launch beach (great if it is a windy day)](https://goo.gl/maps/Qt3m2vcvth4TatUw7)


